kaimono_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name= 'show_main'),
    path('create-barang/', create_barang, name = "create_barang"),
    path('xml/', show_xml, name = "show_xml"),
    path('json/', show_json, name = "show_json"),
    path('xml/<int:id>', show_xml_id, name = "show_xml_id"),
    path('json/<int:id>', show_json_id, name = "show_json"),
    path('register/', register, name = 'register'),
    path('login/', login_user, name = "login"),
    path('logout/', logout_user, name = "logout"),
    path('test/', test, name = "test"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Barang(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField(blank=True, default='')
    harga = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

main/forms.py
from django.forms import ModelForm
from main.models import Barang

class BarangForm(ModelForm):
    class Meta:
        model = Barang
        fields = ["name", "amount", "description", "harga"]

main/views.py
from django.shortcuts import render, redirect
from main.models import Barang
from main.forms import BarangForm
from django.http import HttpResponse
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    barangs = Barang.objects.filter(user=request.user)
    
    context = {
        'name' :  request.user.username,
        'class' : "PBP A",
        'barangs' : barangs,
        'last_login': request.COOKIES['last_login']
    }
    return render(request, "main.html", context)


def create_barang(request):
    form = BarangForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        barang = form.save(commit=False)
        barang.user = request.user
        barang.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_barang.html", context)
 
def test(request):
    return render(request,"test.html")

def show_xml(request):
    data = Barang.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type = "application/xml")

def show_json_id(request, id):
    data = Barang.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data),content_type = "application/json")

def show_xml_id(request, id):
    data = Barang.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("xml", data), content_type = "application/xml")

def show_json(request):
    data = Barang.objects.all()
    return HttpResponse(serializers.serialize("json", data),content_type = "application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
        
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

main/templates/create_barang.html
{% extends 'base.html' %} {% block content %}
<h1>Add New Barang</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add Barang" />
      </td>
      
    </tr>
  </table>
  
</form>
<a href="{% url 'main:show_main'%}">

    <button>Halaman utama</button>
</a>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{%load static%}

{% block meta%} 
  <title>Login</title>
  <link rel="stylesheet"  href="{% static 'css/login.css' %}"/>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
{% endblock meta %}

{% block content %}

<div class="login-container">
  <div class = "login">
    <h1 class >Log in</h1>

    <div class = "login-form">
      <form method="POST" action="">
        {% csrf_token %}
        <table>
          <tr>
            <td>Username:</td>
            <td>
              <input
                type="text"
                name="username"
                placeholder="Username"
                class="form-control"
              />
            </td>
          </tr>

          <tr>
            <td>Password:</td>
            <td>
              <input
                type="password"
                name="password"
                placeholder="Password"
                class="form-control"
              />
            </td>
          </tr>

          <tr>
            <td></td>
            <td><input class="btn login_btn" type="submit" value="Login" /></td>
          </tr>
        </table>
      </form>
    </div>

    
    
    <div class="register">
      <p>Don't have an account yet?</p>
       <a href="{% url 'main:register' %}"><button class="registerbtn">Register Now</button></a>
    </div> 
    
    <div id="invalidinput">
        {% if messages %}
        <ul>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
    </div>
    
  </div>
</div>
</body>
<script>
  function myFunction() {
    var x = document.getElementById("invalidinput");
    x.className = "show";
    setTimeout(function(){ x.className = x.className.replace("show", ""); }, 8000);
  }
</script>
{% endblock content %}

main/templates/main.html
{% extends "base.html" %} 
{% load static %}
{% block meta %}
<title>Main</title>
<link rel="stylesheet"  href="{% static 'css/main.css' %}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
{% endblock meta %} 
{% block content%}
<h1>買い物 Tracker</h1>

<h5>Name: {{ name }}</h5>
<h5>Class:{{ class }} </h5>
<h5>Sesi terakhir login: {{last_login}}</h5>


    {% comment %} Berikut cara memperlihatkan data produk di bawah baris ini
    {%endcomment %}
    <div class="card">
        {% for barang in barangs %}
        
        <div class="container">
            <h4>Nama : {{barang.name}}</h4>
            <h4>Jumlah :{{barang.amount}}</h4>
            <h4>Deskripsi :{{barang.description}}</h4>
            <h4>Tanggal {{barang.date_added}} </h4>
            <h4>Harga : {{barang.harga}} Rupiah</h4>
            
        </div>
            <!--<a href="{ url 'main:edit_book' book.pk %}"> -->
            
          
                <button>
                    Edit
                </button>
            </a>
            <!-- <a href="{ url 'main:delete_book' book.pk %}">-->
            
                <button>
                    Delete
                </button>
            </a>
        
    
    {% endfor %}
    </div>
    

<br/>
<a href="{%url 'main:create_barang'%}">

    <button>Add New Barang</button>
</a>

<a href="{% url 'main:logout' %}">

    <button>Logout</button>
  </a>
{%endblock content%}

main/templates/register.html
{% extends 'base.html' %} 
{%load static%}

{% block meta %}
<title>Register</title>
<link rel="stylesheet"  href="{% static 'css/register.css' %}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
{% endblock meta %} 

{% block content %}

<div class="register-container">
  <div class="register">
    <h1>Register</h1>

    <div class="register-form">
      <form method="POST">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
          <tr>
            <td></td>
            <td><input class="daftar" type="submit" name="submit" value="Daftar" /></td>
           
          </tr>
        </table>
      </form>
    </div>

    <div class="login">
      <p>Sudah ada akun?</p>
       <a href="{% url 'main:login' %}"><button class="loginbtn">Login</button></a>
    </div> 

      <div class="pesan">
        {% if messages %}
          <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

main/templates/test.html
{% extends "base.html" %} {% block content%}
<h1>買い物 Tracker</h1>

<h5>Name:</h5>
<p>{{ name }}</p>
<!-- Ubahlah sesuai dengan nama kamu -->
<h5>Class: </h5>
<p>{{ class }}</p>
<!-- Ubahlah sesuai dengan kelas kamu -->
<h5>Sesi terakhir login: {{last_login}}</h5>

<table>
    <tr>
        <th>Name</th>
        <th>Page</th>
        <th>Description</th>
        <th>Date Added</th>
        <th>Harga</th>

    </tr>
    {% comment %} Berikut cara memperlihatkan data produk di bawah baris ini
    {%endcomment %}
    {% for barang in barangs %}
    <tr>
        <th>{{barang.name}}</th>
        <th>{{barang.amount}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.date_added}} </th>
        <th>{{barang.harga}} Rupiah</th>
        <td>
            <!--<a href="{ url 'main:edit_book' book.pk %}"> -->
            
          
                <button>
                    Edit
                </button>
            </a>
            <!-- <a href="{ url 'main:delete_book' book.pk %}">-->
            
                <button>
                    Delete
                </button>
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
<br/>
<a href="{%url 'main:create_barang'%}">

    <button>Add New Barang</button>
</a>

<a href="{% url 'main:logout' %}">

    <button>Logout</button>
  </a>
{%endblock content%}{% load static %}
{% block content%}
<h1>買い物 Tracker</h1>

<h5>Name:</h5>
<p>{{ name }}</p>
<!-- Ubahlah sesuai dengan nama kamu -->
<h5>Class: </h5>
<p>{{ class }}</p>
<!-- Ubahlah sesuai dengan kelas kamu -->
<h5>Sesi terakhir login: {{last_login}}</h5>

<table>
    <tr>
        <th>Name</th>
        <th>Page</th>
        <th>Description</th>
        <th>Date Added</th>
        <th>Harga</th>

    </tr>
    

    <div class="card">
        {% for barang in barangs %}
    <tr>
        <th>{{barang.name}}</th>
        <th>{{barang.amount}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.date_added}} </th>
        <th>{{barang.harga}} Rupiah</th>
        <td>
    </div>
    
            <!--<a href="{ url 'main:edit_book' book.pk %}"> -->
            
          
                <button>
                    Edit
                </button>
            </a>
            <!-- <a href="{ url 'main:delete_book' book.pk %}">-->
            
                <button>
                    Delete
                </button>
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
<br/>
<a href="{%url 'main:create_barang'%}">

    <button>Add New Barang</button>
</a>

<a href="{% url 'main:logout' %}">

    <button>Logout</button>
  </a>
{%endblock content%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
 
<head>
    
    
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta%} {% endblock meta %}
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> -->
    
</head>

<body>
  
    <!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">Welcome to 買い物 tracker</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url "main:show_json"%}">Data in JSON</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url "main:show_xml"%}">Data in xml</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav> -->
    {% block content %} 
    
    {% endblock content %}
    
</body>
</html>